import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/Navbar/Navbar';
import CategoryBar from '@/components/CategoryBar/CategoryBar';
import { FilterProvider } from '@/utils/FilterContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// TODO! try antialised font smoothing change all a tags to use next/link
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <FilterProvider>
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          <Navbar />
          <CategoryBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
    // </FilterProvider>
  );
}
